language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build  -t annantguptacs15/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true annantguptacs15/docker-react npm run test